name: qualif_ai
description: QualifAI â€” Academic Quality Management & Accreditation System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Dependency Injection
  get_it: ^8.0.2

  # Local Storage
  hive_flutter: ^1.1.0

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Functional Programming
  dartz: ^0.10.1

  # UI / UX
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  fl_chart: ^0.69.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

  # File Handling
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  open_filex: ^4.6.0
  path_provider: ^2.1.4

  # Utils
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  share_plus: ^10.0.3

  # HTTP multipart
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
